### ISSUE TITLE
Dependency Graph weirdness for root component when using processing v2

### ISSUE THREAD

**Issue by malice00** [DependencyTrack/frontend#1026]
### Current Behavior

After activating v2 processing, the root component in a dependency graph is inconsistently rendered either as the name and version of the project (as it was in 4.11.x) or as a PURL. I'm not quite sure when/why it chooses to do one or the other, but I'd prefer it to use the previous way as to keep in line with all projects that were created before 4.12.

### Steps to Reproduce

1. Not sure, will do some more testing to try and figure out if this is random or reproducible

### Expected Behavior

I expect the displayed name in the graph to be consistent between projects and prefer it to be the 'name version'-variant as it was before 4.12.

### Dependency-Track Frontend Version

4.12.0

### Browser

Mozilla Firefox

### Browser Version

130.0.1

### Operating System

macOS

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [x] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this defect was already reported

**Comment by malice00** [comment]
So, further testing seems to point at the fact that the projects that show 'name version' have sub-components defined in the SBOM (so metadata > component > components), whereas the projects that show the PURL have only a root component...

Maybe this is actually an issue for the DT repo? I started posting it here because I had this behavior in the UI, but now I'm not so sure if this is the right place...

**Comment by nscuro** [comment]
Same cause as https://github.com/DependencyTrack/dependency-track/issues/3978#issuecomment-2323046771.

Processing V1 did not import `metadata.component.purl` into the project but V2 does. The code of the dependency graph prefers PURL over name+version: https://github.com/DependencyTrack/frontend/blob/4ccfd8bc8ef18a3db93dcf430a8cc6f1709266b3/src/views/portfolio/projects/ProjectDependencyGraph.vue#L531-L550

Given that projects are otherwise referred to by name and version throughout the application, I do agree that the dependency graph should follow that, and consistently use name and version for the root node.

**Comment by nscuro** [comment]
How are you testing? Is it still showing the PURL for the project node?

It could be that the old version is still cached in your browser.

**Comment by nscuro** [comment]
You shouldn't have to do it. https://github.com/DependencyTrack/frontend/pull/1050 should void the need to clear caches manually.

**Comment by malice00** [comment]
Great update, but that wasn't in the other branch I tested yet, so... 😉

**Comment by nscuro** [comment]
Oh, yeah, I meant to say I took your experience as a reason to implement #1050. Since asking you to clear your cache made me realize how off that is. 😅
