### ISSUE TITLE
Update frontend for CVE-2023-35945

### ISSUE THREAD

**Issue by aescanero-accenture** [DependencyTrack/frontend#569]
### Current Behavior

Actually dependencytrack/frontend v4.8.1 suffers from vulnerability on nginx CVE-2023-35945.
Dependabot updates the Docker.alpine, but no new version/hotfix has been released.

Please update the release to resolve this vulnerability.

### Steps to Reproduce

trivy image --severity HIGH,CRITICAL docker.io/dependencytrack/frontend:4.8.1

### Expected Behavior

CVE-2023-35945 must be resolved by update container release.

### Dependency-Track Frontend Version

4.8.1

### Browser

Other

### Operating System

Other

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
We do not push hotfix releases unless we have evidence that a vulnerability is indeed exploitable, and has a high enough impact to justify a hotfix.

I don't see this being true here. Other than the `nghttp2` package being *present* in the container, there's no evidence of this being exploitable. The CVE was in fact explicitly raised against Envoy, not NGINX or even the `nghttp2` library directly.

Checking what package actually depends on the vulnerable library tells me it's just `curl`, which is also not used by NGINX:

```shell
$ docker run -it --rm --entrypoint /bin/sh docker.io/dependencytrack/frontend:4.8.1

$ apk info --rdepends nghttp2-libs
nghttp2-libs-1.51.0-r0 is required by:
libcurl-8.0.1-r0

$ apk info --rdepends libcurl
libcurl-8.0.1-r0 is required by:
curl-8.0.1-r0

$ apk info --rdepends curl
curl-8.0.1-r0 is required by:

```

If you find this vulnerability to be exploitable in a way that affects the DT frontend application, we'll be happy to push out a hotfix. Otherwise, the fix will be released with the upcoming 4.9 release.
