### ISSUE TITLE
Unable to see vulnerability status in Components view

### ISSUE THREAD

**Issue by jornraastad** [DependencyTrack/frontend#57]
It would be very useful to see the vulnerability status for each listed component in the Components view. Individual  vulnerability status for each component provides useful insight to help remediation.
Such status was provided in an earlier version of DepTrack.

**Comment by stevespringett** [comment]
Can you clarify 'vulnerability status'? What is meant by that?  Also, what version of DT (or the DT frontend) are you referring to?

**Comment by jornraastad** [comment]
Frontend v1.2.0
Build ID: 6fea7979-2506-4d24-a485-0a5481392b20
Built On: 10 Feb 2021 at 03:29:25

What I mean by Vulnerability status: Risk score and Red-orange-yellow-green graphics showing number of vulnerabilities associated with the component.
Similar to what I can see in the Project view if I go to Components tab.

**Comment by stevespringett** [comment]
Ok, I think I understand. The general assumption was that if a user was looking for a specific use of a component, they would already know it has risk. But you're saying is that it would still be useful to have the risk score and the vulnerability severity bar in the following component search results. Is that correct?
<img width="1676" alt="Screen Shot 2021-02-24 at 10 53 10 AM" src="https://user-images.githubusercontent.com/3878933/109036130-eab38800-768e-11eb-9582-03504716aed8.png">

**Comment by jornraastad** [comment]
Yes, that is correct. It helps me prioritize remediation work by "working backwards" from the highest rated vulnerabilities reported.
Thank you for your understanding!

**Comment by stevespringett** [comment]
Support for this was partially implemented in the UI, but due to tech limitations and delays around the release of 4.0, the feature was disabled. This has been worked out. With the next release of the UI, the search screen will remain the same, however, there's now a refresh button and an option to select the fields you want to see in the table. The risk score and vulnerabilities fields are unchecked by default. Checking them will result in the fields being displayed and populated with data.
<img width="1674" alt="Screen Shot 2021-02-24 at 10 06 12 PM" src="https://user-images.githubusercontent.com/3878933/109101991-74923e00-76ed-11eb-8de6-b978c4eeeed3.png">

**Comment by jornraastad** [comment]
Thank you very much!

**Comment by stevespringett** [comment]
Will be included in Dependency-Track v4.2

**Comment by wargamez** [comment]
I just upgraded to 4.2 and I am able to see that refresh button and an option to select the fields on the components view, but it does not stick on page refresh/reload (Using Chrome)
