### ISSUE TITLE
improve entrypoint

### ISSUE THREAD

**Issue by davidkarlsen** [DependencyTrack/frontend#60]
### Current Behavior:

https://github.com/DependencyTrack/frontend/blob/master/docker/docker-entrypoint.sh#L6
checks for a mount, this does work well with configmaps in kubernetes. Configmaps is seen as a good practice.

### Proposed Behavior:
could it instead simply check that the file exists, and if it does, ignore it. Also note that in case of configmaps it is not a ordinary file, but rather a symlink:
```
/app/static # ls -l conf*
lrwxrwxrwx    1 root     root            18 Mar  2 19:56 config.json -> ..data/config.json
/app/static # ls -l /app/static/config.json 
lrwxrwxrwx    1 root     root            18 Mar  2 19:56 /app/static/config.json -> ..data/config.json
/app/static # ls -l /app/static/..data
lrwxrwxrwx    1 root     root            31 Mar  2 19:56 /app/static/..data -> ..2021_03_02_19_56_07.520397086
/app/static # 
```

**Comment by davidkarlsen** [comment]
related: https://github.com/DependencyTrack/frontend/issues/48

**Comment by davidkarlsen** [comment]
@namlock2001 want to have a stab at this too?

**Comment by muellerst-hg** [comment]
One issue I found is that docker-entrypoint checks for `/static/config.json` (absolute path) but later writes to `./static/config.json` (relative path) and nginx serves the latter one. As a result, having a volume mount at `/static/config.json` ends up with the config file from the docker image which has no values set.
In order to get configmap setup really up and running, two volumeMounts are required, one mounting at `/static/config.json` and another one at `/opt/owasp/dependency-track-frontend/static/config.json`

**Comment by muellerst-hg** [comment]
Seems there's also a regression, when nginx root dir was moved from /app to /opt/owasp/dependency-track-frontend  but docker-compose was not updated. https://github.com/DependencyTrack/frontend/commit/d12ddfa9dcc80bb7ac262eaec70c214a77b81a38#diff-6e3cd4368541f4b438a0ce9dfe5b45e3a04426f80b43546092e76f088bd2e8dc
