### ISSUE TITLE
Project Version Picker Should Indicate Inactive Versions

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/frontend#844]
### Current Behavior

When viewing a project, one can switch to a different version of the project using a dropdown picker.  The list of available versions does not indicate which are active and which are inactive

![image](https://github.com/DependencyTrack/frontend/assets/4938718/6c550ab0-c3b0-42fa-b7e5-85559984594d)

### Proposed Behavior

The list of versions displayed in the version picker dropdown should indicate when a version is inactive.  Perhaps by using strikethrough? 

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Note, the API will need to be updated to include the `active` field. 

The code for querying the version information displayed in this dropdown is here: https://github.com/DependencyTrack/dependency-track/blob/06e6eba67e67fa173a7b1ea46b46515962e61b13/src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java#L1209-L1215

**Comment by aravindparappil46** [comment]
Hi folks,
I started working on this and wanted to discuss two possible options:

**Option 1 - Warning Icon**

![image](https://github.com/DependencyTrack/frontend/assets/43161107/6df617bd-e95a-49ab-a650-50cb2ae8f7de)


**Option 2 - Strikethrough**

![image](https://github.com/DependencyTrack/frontend/assets/43161107/eb224292-a3b5-40d9-bd43-a4328498a2a4)


I'm leaning towards **Option 1**, since
- We do not have to introduce a new UX pattern in the app (the strikethrough) since the ⚠️ icon currently exists in the `Components` page
- We could use the same icon at a project level, for addressing #843 

Eager to know your thoughts!

**Comment by nscuro** [comment]
@aravindparappil46 I think using ⚠️ might be confusing on first look, since we also use that to point out outdated versions. Also, a project being inactive is not something that requires attention, it's more of a BAU thing if that makes sense.

Perhaps using a "muted" text style would make sense, indicating that those items are less important than the rest. We could further sort the version list such that inactive versions are grouped towards the bottom of the dropdown. 

Another option - note that I haven't looked at how the dropdown is currently implemented - could be to use `b-dropdown-group` to provide a clear separation between active and inactive versions: https://bootstrap-vue.org/docs/components/dropdown#b-dropdown-group

**Comment by aravindparappil46** [comment]
That makes sense, @nscuro . Thanks!

I really liked the last option of adding a group for inactive versions, so went with that in the PR #862 (can make changes, of course).

Here is how it looks:
![image](https://github.com/DependencyTrack/frontend/assets/43161107/167d60ca-9619-449c-b713-5d6c12a13281)

**Comment by mieliespoor** [comment]
Would it be a manual action then to set the version inactive? In other words, it would be a deliberate decision to set a version inactive, and if you don't, you will have multiple versions active?

**Comment by msymons** [comment]
@mieliespoor 

> Would it be a manual action then to set the version inactive?

Yes.  In the UI, this is set via the dialog displayed when clicking the "View Details" button for a project.  Flagging a project as inactive is a great way to ensure that it does not "pollute" the portfolio metrics.

I also tend to have multiple projects that exist purely for testing purposes and which might not be used for months at a time.  Thus,  it is easiest to make them inactive and then "turn them on again" as and when they are needed.
